### PR TITLE
fix: add backwards compatibility for nvim 0.9

### PR DESCRIPTION
**Pull request by chrisgrieser**

### CODE REVIEW

**Comment by icholy** [comment]
Thanks for opening this, I really appreciate it.

**Comment by chrisgrieser** [comment]
btw, if you add a `stylua.toml` and/or `.editorconfig`, such formatting issues would be much easier to catch 🙏

**Comment by icholy** [comment]
I have a `.luacheckrc` at the root. Is `stylua` the more commonly used tool?

**Comment by icholy** [comment]
I just tested your fork and 0.9 doesn't seem to have `vim.lsp.get_clients`. I think we'll need to use `vim.lsp.buf_get_clients` instead. I can do that myself ~~if you don't feel like it though, so let me know.~~

edit: I'll change the call after merging this.

**Comment by chrisgrieser** [comment]
> I have a `.luacheckrc` at the root. Is `stylua` the more commonly used tool?

Yes, by far. Among other things, [the last luacheck commit was 6 years ago](https://github.com/mpeterv/luacheck).

**Comment by icholy** [comment]
@chrisgrieser does the lua/neovim community have a convention for indentation?

**Comment by chrisgrieser** [comment]
@icholy not that I know of. I think every plugin author decides themselves, and sets that in their config file, I think. Adding an `.editorconfig` (supported by neovim core) is and a `.stylua.toml` as the most popular lua formatter should be enough from what I can tell.

**Pull request merged**
